services:
  pgdatabase:
    image: postgres:13
    container_name: postgres_compose_container
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'ny_taxi_2019'
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - '5431:5432'
  pgadmin1:
    image: dpage/pgadmin4
    container_name: pgadmin_compose_container
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '8080:80'
    volumes:
      - "./pgadmin4:/var/lib/pgadmin/data:rw"